/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.1/samples
 */

import java.io.ByteArrayOutputStream

tasks.register<Exec>("test"){
    commandLine("turtle", "--validate", "brittany.ttl")
}

tasks.register<Exec>("query"){
    val arg: String by project
    if (project.hasProperty("arg")) {
        val inferredFileName = "brittany-inferred.xml"
        val inferredFile = File(inferredFileName)
        val outputText: String = ByteArrayOutputStream().use { outputStream ->
            project.exec {
                commandLine("pellet", "extract", "brittany.ttl")
                standardOutput = outputStream
            }
            outputStream.toString()
        }
        inferredFile.writeText(outputText)
        commandLine("arq", "--data", inferredFileName, "--query", "query/" + arg + ".rq")
        doLast {
            inferredFile.delete()
        }
    } else {
        println("No query specified. Use the 'arg' property to specify a query.")
    }
}
