/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.1/samples
 */

tasks.register<Exec>("test"){
    commandLine("turtle", "--validate", "brittany.ttl")
}

tasks.register<Exec>("query"){
    val arg: String by project
    if (project.hasProperty("arg")) {
        commandLine("arq", "--data", "brittany.ttl", "--query", "query/" + arg + ".rq")
    } else {
        println("No query specified. Use the 'arg' property to specify a query.")
    }
}
