PREFIX : <https://brittany-persistence-service.herokuapp.com/#>

SELECT DISTINCT ?greenhouse ?environment ?plant

WHERE {
    OPTIONAL { ?greenhouse :hasEnvironment ?environment .}
    ?environment :hasEnvironmentPlant ?plant .
}

ORDER BY ?greenhouse ?environment ?plant
