PREFIX : <https://brittany-persistence-service.herokuapp.com/#>

SELECT DISTINCT ?greenhouse ?environment (COUNT(?plant) as ?plant_count)

WHERE {
    OPTIONAL { ?greenhouse :hasEnvironment ?environment . }
    ?environment :hasPlant ?plant .
}

GROUP BY ?greenhouse ?environment
